### ISSUE TITLE
Bravo et petit plus

### ISSUE THREAD

**Issue by Nours42** [maitreverge/atelier_github_branchs#14]
Franchement faire un cours sur le GIT **avec** un atelier et des trucs à faire c'est chaud donc vraiment chapeau bas.

Un truc à ajouter à votre présentation le GIT fetch. 

git-fetch - Download objects and refs from another repository

ça download les mises à jour server mais sans les appliquer. ça permet de ne pas faire un pull qui écraserait certaines modifications. 

Exemple, j'ai modifié main.js, toi aussi et je suis sur un autre fichier, tu me dis "j'ai mis a jour main.js" "ah mince moi aussi... bon ben je vais le fetche et faire une version qui intègre tes modifs et les miennes"

**Comment by maitreverge** [comment]
Merci pour ton retour, je prends note de tes suggestions pour `git fetch` 🚀
